language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - py.test --cov-config .coveragerc --flake8 --cov=pindo_cli pindo_cli/tests